models.py
from extensions import db
from flask_wtf import FlaskForm
from wtforms.fields.html5 import DateField, IntegerField, EmailField
from wtforms.validators import DataRequired
from wtforms import validators, SubmitField, ValidationError

# Custom validator for weekends exclusion
class WeekdayValidator(object):
    def __call__(self, form, field):
        if field.data and field.data.isoweekday() > 6:
            raise ValidationError("Sorry, we are closed on weekends. Please choose a different date.")

# Creating form class for booking system
class InfoForm(FlaskForm):
    book_date = DateField('Booking Date', format='%Y-%m-%d', validators=[WeekdayValidator(), DataRequired()])
    guests = IntegerField('Number of Guests', [validators.DataRequired(), validators.NumberRange(min=0, max=30, message='Sorry, maximum number of guests per day is 30.')])
    email = EmailField('Email Address', [validators.DataRequired()])
    submit = SubmitField('Book Now')

# Creating data base models with implementation of one-to-many relationship
class Date(db.Model):
    __tablename__ = 'date'
    id = db.Column(db.Integer, primary_key=True)
    book_date = db.Column(db.String(80), nullable=False)
    guests_total = db.Column(db.Integer, nullable=False)
    details_id = db.relationship('Details', backref='date', lazy=True)

    def __init__(self, book_date, guests_total):
        self.book_date = book_date
        self.guests_total = guests_total

    def __repr__(self):
        return f'<Date: {self.id} {self.book_date} {self.guests_total}>'

class Details(db.Model):
    __tablename__ = 'details'
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(120), nullable=False)
    guests = db.Column(db.Integer, nullable=False)
    date_id = db.Column(db.Integer, db.ForeignKey('date.id'))

    def __repr__(self):
        return f'<Details: {self.id} {self.email} {self.guests}>'
    
class Menu:
    def __init__(self):
        
        self.fronts = ['food1.png', 'food2.png', 'food3.png']
        self.ranks = [1,2,3]
        self.names = ['3 Course Set', '6 Course Set', '9 Course Set']
        self.contents_1 = ['prawn2.png', 'prawn3.png', 'nut1.png']
        self.contents_2 = ['meat.png', 'fruit2.png', 'prawn1.png']
        self.contents_3 = ['cheese.png', 'nut2.png', 'fish4.png']
        self.stats_1 = ['50.00', '70.00', '90.00']
        self.stats_2 = ['100.00', '140.00', '180.00']

routes.py
from flask import redirect, url_for, render_template, session, request
from flask import Blueprint
from models import InfoForm, Date, Details, Menu
from flask import Blueprint
from extensions import db

main = Blueprint('main', __name__)

@main.route('/')
def index():
    return render_template('index.html')

@main.route('/menu')
def menu():

    menu = Menu()
    fronts= menu.fronts
    ranks = menu.ranks
    names = menu.names
    contents_1 = menu.contents_1
    contents_2 = menu.contents_2
    contents_3 = menu.contents_3
    stats_1 = menu.stats_1
    stats_2 = menu.stats_2

    return render_template('menu.html', fronts=fronts, ranks=ranks,  names=names, contents_1=contents_1,
                contents_2=contents_2, contents_3=contents_3, stats_1=stats_1, stats_2=stats_2)

@main.route('/form', methods=['GET','POST'])
def form():
    # Instantiating form class
    form = InfoForm()
    
    # Performing form validation
    if form.validate_on_submit():
        bookdate = form.book_date.data
        guests = form.guests.data
        email = form.email.data
        
        # Ensuring even parity for number of guests 
        if int(guests) % 2 == 1:
            guests = guests + 1
            
        session['bookdate'] = bookdate
        session['guests'] = guests
        session['email'] = email
        
        # Checking for existing record in data base
        existing_date = Date.query.filter_by(book_date=bookdate).first()
        if not existing_date:
            
            # Creating and saving new data base objects
            new_book_date = Date(book_date=bookdate, guests_total=guests)
            new_detail = Details(email=email, guests=guests, date=new_book_date)
            db.session.add(new_book_date)
            db.session.commit()
            db.session.add(new_detail)
            db.session.commit()
            return redirect('success')
        else:
            
            # Summing up total number of guests
            old_total = existing_date.guests_total
            new_total = int(old_total) + int(guests)
            session['total'] = new_total
            
            # Ensuring that total number of guests does not exceed daily limit of 30 covers
            if new_total > 30:
                error = 'Sorry, we are already fully booked. Please choose a different date.'
                return render_template('form.html', error=error, form=form)
            else:
                existing_date.guests_total = new_total
                new_detail = Details(email=email, guests=guests, date=existing_date)
                db.session.add(new_detail)
                db.session.commit()    
                return redirect('success')
    return render_template('form.html', form=form)

@main.route('/success', methods=['GET','POST'])
def success():
    return render_template('success.html')

@main.route('/result', methods=['GET', 'POST'])
def result():
    try:
        if request.method == "POST":
            booking_date = request.form['date']
            
            # Querying data base for existing bookings on given date
            data = Date.query.filter_by(book_date=booking_date).first()
            total = data.guests_total
            data_id = data.id
            emails = Details.query.filter(Details.date_id == data_id).all()
            return render_template('result.html', total=total, emails=emails)
    except AttributeError:
        
        # Throwing an error if there are no records
        error = 'There are no bookings on the date you have selected!'
        return render_template('admin.html', error=error)
        

@main.route('/admin')
def admin():
    return render_template('admin.html')

# Custom error pages
@main.app_errorhandler(404)
def not_found(e):
    return render_template('404.html'), 404

@main.app_errorhandler(500)
def internal_server_error(e):
    return render_template('500.html'), 500

templates/admin.html
{% extends 'base.html' %}

    {% block stylesheet %}<link rel="stylesheet" href="../static/admin.css">{% endblock %}

    {% block title %}Admin{% endblock %}

    {% block content %}
    <div class="container">
        <form action="{{ url_for('main.result') }}" method='POST' >
            <label>
              Enter Booking Date:
              <input type="date" name="date">
            </label>
            <p><button class="submit">Submit</button></p>
          </form>
          <h3>{{ error }}</h3>
    </div>
    {% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/base.css">
    {% block stylesheet %}{% endblock %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />
    <link rel="shortcut icon" href="../static/images/favicon.ico" type="image/x-icon">
    <link rel="icon" href="../static/images/favicon.ico" type="image/x-icon">
    <title>3 Dining | {% block title %}{% endblock %}</title>
</head>
<body>
    <nav>
        <div class="navigation">
            <a href="{{ url_for('main.index') }}" class="neon-button">3 Dining</a>
            <div class="icons">
                <div class="tooltip">
                    <a href="{{ url_for('main.index') }}"><i class="fas fa-home"></i></a>
                    <span class="tooltiptext">Home</span>
                  </div>
                <div class="tooltip">
                    <a href="{{ url_for('main.form') }}"><i class="fas fa-calendar-check"></i></a>
                    <span class="tooltiptext">Book</span>
                  </div>
                <div class="tooltip">
                    <a href="{{ url_for('main.menu') }}"><i class="fas fa-book-open"></i></a>
                    <span class="tooltiptext">Menu</span>
                  </div>
            </div>
        </div>
    </nav>
    
    {% block content %}{% endblock %}
    
    
</body>
</html>

templates/form.html
{% extends 'base.html' %}

    {% block stylesheet %}<link rel="stylesheet" href="../static/form.css">{% endblock %}

    {% block title %}Book{% endblock %}

    {% block content %}
    <div class="container">
        <form action="" method='POST' name="myform">
            {{ form.csrt_token }}
            <div class="date">
                {{ form.book_date.label }} {{form.book_date(class='date_field')}} {{form.hidden_tag()}}
            </div>
            <div class="guests">
                {{ form.guests.label }} {{form.guests(class='guests_field')}} {{form.hidden_tag()}}
            </div>
            <div class="email">
                {{ form.email.label }} {{form.email(class='email_field')}} {{form.hidden_tag()}}
            </div>
            <div class="submit">
                {{form.submit(class='submit_field')}} 
            </div>
        </form>
        <h2 class="error">{{ error }}</h2>
        {% if form.errors %}
            {% for field_name, field_errors in form.errors|dictsort if field_errors %}
                {% for error in field_errors %}
                    <h2 class="error">{{ error }}</h2>
                {% endfor %}
            {% endfor %}
        {% endif %}
    </div>
    {% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../static/index.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />
    <link rel="shortcut icon" href="../static/images/favicon.ico" type="image/x-icon">
    <link rel="icon" href="../static/images/favicon.ico" type="image/x-icon">
    <title>3 Dining | Home</title>
</head>
<body>
        <div class="container">
            <a href="{{ url_for('main.index') }}" class="neon-button">3 Dining</a>
            <div class="icons">
                <div class="tooltip">
                    <a href="{{ url_for('main.index') }}"><i class="fas fa-home"></i></a>
                    <span class="tooltiptext">Home</span>
                  </div>
                <div class="tooltip">
                    <a href="{{ url_for('main.form') }}"><i class="fas fa-calendar-check"></i></a>
                    <span class="tooltiptext">Book</span>
                  </div>
                <div class="tooltip">
                    <a href="{{ url_for('main.menu') }}"><i class="fas fa-book-open"></i></a>
                    <span class="tooltiptext">Menu</span>
                  </div>
            </div>
        </div>
    <div class="scene">
        <div class="floor"></div>
        <div class="cube">
            <div class="front"></div>
            <div class="back"></div>
            <div class="left"></div>
            <div class="right"></div>
            <div class="top">
                <div class="ball-shadow"></div>
            </div>
            <div class="bottom"></div>
        </div>
        <div class="ball"></div>
    </div>
</body>
</html>

templates/macros.html
{% macro menu(fronts, ranks, names, contents_1, contents_2, contents_3, stats_1, stats_2) %}


  
    <div class="menu">
            <div class="rank">{{ ranks }}</div>
        
        <div class="front">
            <img src="{{ url_for('static', filename = 'images/'+fronts ) }}" alt="">
            
            <h3 class="name">{{ names }}</h3>
       
            <div class="stats">
                <p class="info">Info</p>
                <div class="contents">
                    <img src="{{ url_for('static', filename = 'images/'+contents_1 ) }}" alt="">
                    <img src="{{ url_for('static', filename = 'images/'+contents_2 ) }}" alt="">
                    <img src="{{ url_for('static', filename = 'images/'+contents_3 ) }}" alt="">
                </div>
            </div>
        </div>
       
        <div class="back">
            <div class="pricing-info">
                <p class="menu-stat">{{ stats_1 }}<span>Regular</span></p>
                <p class="menu-stat">{{ stats_2 }}<span>Premium</span></p>
            </div>
            <a href="{{ url_for('main.form') }}"><button class="btn">Manage Your Booking</button></a>
            <div class="contents">
                <div class="set">
                    <p class="name">Set 1</p>
                </div>
                <div class="set">
                    <p class="name">Set 2</p>
                </div>
                <div class="set">
                    <p class="name">Set 3</p>
                </div>
            </div>
        </div>

        <div class="background"></div>
        
        <div class="back"></div>
    </div>
   
 

    

{% endmacro %}

templates/menu.html
{% extends 'base.html' %}
{% from 'macros.html' import menu %}

    {% block stylesheet %}<link rel="stylesheet" href="../static/menu.css">{% endblock %}

    {% block title %}Menu{% endblock %}
       
    {% block content %}
    
    <div class="carts">

        {{ menu(fronts[0], ranks[0], names[0], contents_1[0], contents_2[0], contents_3[0], stats_1[0], stats_2[0]) }}
        {{ menu(fronts[1], ranks[1], names[1], contents_1[1], contents_2[1], contents_3[1], stats_1[1], stats_2[1]) }}
        {{ menu(fronts[2], ranks[2], names[2], contents_1[2], contents_2[2], contents_3[2], stats_1[2], stats_2[2]) }}

    </div>
    
    {% endblock %}

templates/result.html
{% extends 'base.html' %}

    {% block stylesheet %}<link rel="stylesheet" href="../static/result.css">{% endblock %}

    {% block title %}Result{% endblock %}

    {% block content %}
    <div class="container">
        <table>
            <tr>
              <th>Total</th>
              <th>Guests</th>
              <th>Email</th>
            </tr>
            {% for x in emails %}
            <tr>
              <td>{{ total }}</td>
              <td>{{ x.guests }}</td>
              <td>{{ x.email }}</td>
            </tr>
            {% endfor %}
          </table>
    </div>
    {% endblock %}

templates/success.html
{% extends 'base.html' %}

    {% block stylesheet %}<link rel="stylesheet" href="../static/success.css">{% endblock %}

    {% block title %}Success{% endblock %}

    {% block content %}
    <div class="container">
            <h1 class="success">Thank You for Your Reservation!</h1>
            <h4>Booking Date: {{session['bookdate']}}</h4>
            <h4>Number of Guests: {{session['guests']}}</h4>
            <h4>Contact Email: {{session['email']}}</h4>
    </div>
    {% endblock %}